apiVersion: apps/v1
kind: Deployment
metadata:
  name:  agilebd2023
  namespace: demo
spec:
  selector:
    matchLabels:
      app: agilebd2023
  template:
    metadata:
      labels:
        app: agilebd2023
    spec:
      containers:
        - name: agilebd2023
          image: mirajehossain/agilebd2023:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
